version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  hh-blog:
    image: hahyunkim/hxhkim.github.io:1.4.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=hhblog.com
      - VIRTUAL_PORT=80

  mj-blog:
    image: minjung818/minjung00.github.io:1.4.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=mjblog.com
      - VIRTUAL_PORT=80

  sb-blog:
    image: parksubeen/qkrtnqls1216.github.io:1.4.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=sbblog.com
      - VIRTUAL_PORT=80

  jh-blog:
    image: mato94/shims94.github.io:1.4.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=jhblog.com
      - VIRTUAL_PORT=80

  ig-blog:
    image: aaingyunii/aaingyunii.github.io:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=igblog.com
      - VIRTUAL_PORT=80

  js-blog:
    image: juseonlee/assomdevgit.github.io:1.4.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=jsblog.com
      - VIRTUAL_PORT=80
